build:
  stage: build
  script:
    - bash autogen.sh
    - ./configure CFLAGS="-Wall -Werror -fsanitize=undefined -fno-sanitize-recover"
    - make
  artifacts:
    paths:
      - src/ninkasi
      - src/ninkasi_test

test:
  stage: test
  script:
    - bash test/run_tests.bsh
  dependencies:
    - build

deploy:
  stage: deploy
  script:
    - bash autogen.sh
    - ./configure
    - make dist
  dependencies:
    - build
  artifacts:
    paths:
      - ./ninkasi-0.1.tar.gz
