build:
  stage: build
  script:
    - bash autogen.sh
    - ./configure CFLAGS="-Wall -Werror -fsanitize=undefined -fno-sanitize-recover"
    - make
  artifacts:
    paths:
      - src/ninkasi
      - src/ninkasi_test

build:dos:
  stage: build
  script:
    - bash misc/generate_build_batch_file.bsh
    - rundos call build.bat
  artifacts:
    paths:
      - ./A.EXE

test:
  stage: test
  script:
    - src/ninkasi_test -c test/test2.nks
    - bash test/run_tests.bsh
    - dos2unix output_dos.txt
    - diff output_linux.txt output_dos.txt
  dependencies:
    - build
    - build:dos
  artifacts:
    paths:
      - test/test2.nkb

deploy:
  stage: deploy
  script:
    - bash autogen.sh
    - ./configure
    - make dist
  dependencies:
    - build
    - test
  artifacts:
    paths:
      - ./ninkasi-0.1.tar.gz
